// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnSi2W835apxEHXptN_JWuxKZd15GbYeI',
    appId: '1:276322031180:web:c2111946d7e8dbf40fc6e9',
    messagingSenderId: '276322031180',
    projectId: 'spacenews-core',
    authDomain: 'spacenews-core.firebaseapp.com',
    databaseURL: 'https://spacenews-core-default-rtdb.firebaseio.com',
    storageBucket: 'spacenews-core.firebasestorage.app',
    measurementId: 'G-29MGD7D9QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS90YBuaPUxI6aWkLNSQPka8Und7iK2So',
    appId: '1:276322031180:android:30c14b19dac7bfd30fc6e9',
    messagingSenderId: '276322031180',
    projectId: 'spacenews-core',
    databaseURL: 'https://spacenews-core-default-rtdb.firebaseio.com',
    storageBucket: 'spacenews-core.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnSi2W835apxEHXptN_JWuxKZd15GbYeI',
    appId: '1:276322031180:web:d1c1970cc5f627f30fc6e9',
    messagingSenderId: '276322031180',
    projectId: 'spacenews-core',
    authDomain: 'spacenews-core.firebaseapp.com',
    databaseURL: 'https://spacenews-core-default-rtdb.firebaseio.com',
    storageBucket: 'spacenews-core.firebasestorage.app',
    measurementId: 'G-V0869RZG7H',
  );
}
